// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalApp.API.Data;

namespace PortalApp.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190527152005_InitialOne")]
    partial class InitialOne
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<int>("UserId");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("PortalApp.API.Dtos.UserForListDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Username");

                    b.Property<Guid?>("WfConfigsSerializedId");

                    b.HasKey("Id");

                    b.HasIndex("WfConfigsSerializedId");

                    b.ToTable("UserForListDto");
                });

            modelBuilder.Entity("PortalApp.API.Models.ContentConfigsSerialized", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ContentType");

                    b.Property<string>("FieldDisplayName");

                    b.Property<string>("FieldName");

                    b.Property<string>("Formula");

                    b.Property<string>("Group");

                    b.HasKey("Id");

                    b.ToTable("ContentConfigsSerialized");
                });

            modelBuilder.Entity("PortalApp.API.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("KeyIndex");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("PortalApp.API.Models.DepartmentV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("DepartmentId");

                    b.Property<bool>("Disabled");

                    b.Property<string>("DisplayNameEng");

                    b.Property<string>("DisplayNameKaz");

                    b.Property<string>("DisplayNameRus");

                    b.Property<string>("FromNameEng");

                    b.Property<string>("FromNameKaz");

                    b.Property<string>("FromNameRus");

                    b.Property<string>("Name");

                    b.Property<int>("Priority");

                    b.Property<Guid>("RegionId");

                    b.Property<string>("ShortName");

                    b.Property<string>("ToNameEng");

                    b.Property<string>("ToNameKaz");

                    b.Property<string>("ToNameRus");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RegionId");

                    b.ToTable("DepartmentVs");
                });

            modelBuilder.Entity("PortalApp.API.Models.DocumentConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DocumentType");

                    b.HasKey("Id");

                    b.ToTable("DocumentConfigs");
                });

            modelBuilder.Entity("PortalApp.API.Models.DocumentConfigVs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Author");

                    b.Property<string>("Category");

                    b.Property<bool>("CloseDocumentFunction");

                    b.Property<string>("ContentConfigs");

                    b.Property<bool>("CopyDocumentFunction");

                    b.Property<bool>("CreateControlcardFunction");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("DocumentConfigId");

                    b.Property<bool>("NeedRegister");

                    b.Property<bool>("ReadOnly");

                    b.Property<string>("Title");

                    b.Property<string>("TitleGeneration");

                    b.Property<string>("WfConfig");

                    b.HasKey("Id");

                    b.HasIndex("DocumentConfigId");

                    b.ToTable("DocumentConfigVs");
                });

            modelBuilder.Entity("PortalApp.API.Models.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NameEn");

                    b.Property<string>("NameKz");

                    b.Property<string>("NameRu");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("PortalApp.API.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("PortalApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("Created");

                    b.Property<Guid?>("DepartmentVId");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<DateTime>("LastActive");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentVId");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("PortalApp.API.Models.UserRole", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("PortalApp.API.Models.UserTemp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cabinet");

                    b.Property<string>("DepartmentName");

                    b.Property<string>("DeputyUserName");

                    b.Property<bool?>("Disabled");

                    b.Property<string>("DisplayNameEng");

                    b.Property<string>("DisplayNameKaz");

                    b.Property<string>("DisplayNameRus");

                    b.Property<string>("Email");

                    b.Property<string>("FromNameEng");

                    b.Property<string>("FromNameKaz");

                    b.Property<string>("FromNameRus");

                    b.Property<DateTime?>("LastLogin");

                    b.Property<string>("Mobile");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<string>("Position");

                    b.Property<string>("PositionEng");

                    b.Property<string>("PositionKaz");

                    b.Property<string>("PositionRus");

                    b.Property<string>("PrefferedCulture");

                    b.Property<int?>("Priority");

                    b.Property<string>("RegionString");

                    b.Property<string>("Roles");

                    b.Property<byte[]>("TimeStamp");

                    b.Property<string>("ToNameEng");

                    b.Property<string>("ToNameKaz");

                    b.Property<string>("ToNameRus");

                    b.HasKey("Id");

                    b.ToTable("UserTemps");
                });

            modelBuilder.Entity("PortalApp.API.Models.UserV", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("DepartmentVId");

                    b.Property<bool>("Disabled");

                    b.Property<string>("DisplayNameEng");

                    b.Property<string>("DisplayNameKaz");

                    b.Property<string>("DisplayNameRus");

                    b.Property<string>("FromNameEng");

                    b.Property<string>("FromNameKaz");

                    b.Property<string>("FromNameRus");

                    b.Property<int>("Priority");

                    b.Property<string>("ToNameEng");

                    b.Property<string>("ToNameKaz");

                    b.Property<string>("ToNameRus");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentVId");

                    b.HasIndex("UserId");

                    b.ToTable("UserVs");
                });

            modelBuilder.Entity("PortalApp.API.Models.Value", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Values");
                });

            modelBuilder.Entity("PortalApp.API.Models.WfConfigsSerialized", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Computed");

                    b.Property<bool>("Editable");

                    b.Property<int>("Priority");

                    b.Property<int?>("ProcessTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ProcessTypeId");

                    b.ToTable("WfConfigsSerialized");
                });

            modelBuilder.Entity("PortalApp.API.Models.WfProcessIteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("WfProcessIteration");
                });

            modelBuilder.Entity("PortalApp.API.Models.WfProcessResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("WfProcessResult");
                });

            modelBuilder.Entity("PortalApp.API.Models.WfProcessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("WfProcessType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("PortalApp.API.Models.Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("PortalApp.API.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("PortalApp.API.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("PortalApp.API.Models.User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PortalApp.API.Dtos.UserForListDto", b =>
                {
                    b.HasOne("PortalApp.API.Models.WfConfigsSerialized")
                        .WithMany("Ous")
                        .HasForeignKey("WfConfigsSerializedId");
                });

            modelBuilder.Entity("PortalApp.API.Models.DepartmentV", b =>
                {
                    b.HasOne("PortalApp.API.Models.Department", "Department")
                        .WithMany("DepartmentVs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PortalApp.API.Models.Region")
                        .WithMany("DepartmentVs")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PortalApp.API.Models.DocumentConfigVs", b =>
                {
                    b.HasOne("PortalApp.API.Models.DocumentConfig")
                        .WithMany("DocumentConfigVs")
                        .HasForeignKey("DocumentConfigId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PortalApp.API.Models.User", b =>
                {
                    b.HasOne("PortalApp.API.Models.DepartmentV")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentVId");
                });

            modelBuilder.Entity("PortalApp.API.Models.UserRole", b =>
                {
                    b.HasOne("PortalApp.API.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PortalApp.API.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PortalApp.API.Models.UserV", b =>
                {
                    b.HasOne("PortalApp.API.Models.DepartmentV", "DepartmentV")
                        .WithMany()
                        .HasForeignKey("DepartmentVId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PortalApp.API.Models.User", "User")
                        .WithMany("UserVs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PortalApp.API.Models.WfConfigsSerialized", b =>
                {
                    b.HasOne("PortalApp.API.Models.WfProcessType", "ProcessType")
                        .WithMany()
                        .HasForeignKey("ProcessTypeId");
                });
#pragma warning restore 612, 618
        }
    }
}
